FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# 任务管理

任务管理API

## 发布任务

### 任务 [/task]

#### 发布任务 [POST]

+ Request (application/json)

        {
            
        }
        
+ Response (application/json)

    + Body
    
            {
            
            }

#### 获取基本信息 [GET]

### 下属组织及成员 [/task/orgs]

###